import express from 'express';

/**
 * This interface extends the express.Request interface with request context.
 */
export type RequestContext = express.Request & {
    /**
     * Request id generated by the logger middleware.
     */
    rid: string;

    /**
     * Request start time.
     */
    startTime: number;
};
